-- Migration: Add AI Analytics Tables
-- Purpose: Store AI-generated metrics, schedules, and forecasts for data-driven dashboard

-- 1. AI Analytics Table (for dashboard metrics like NRW, uptime, etc.)
CREATE TABLE IF NOT EXISTS ai_analytics (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  metric_name TEXT NOT NULL,
  metric_value JSONB NOT NULL,
  calculated_at TIMESTAMP DEFAULT NOW(),
  valid_until TIMESTAMP,
  metadata JSONB,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_ai_analytics_metric_name ON ai_analytics(metric_name);
CREATE INDEX idx_ai_analytics_calculated_at ON ai_analytics(calculated_at DESC);

-- 2. Energy Schedules Table (from Energy Optimizer Agent)
CREATE TABLE IF NOT EXISTS energy_schedules (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  schedule_date DATE NOT NULL,
  pump_id UUID REFERENCES valves_pumps(id) ON DELETE CASCADE,
  pump_name TEXT,
  hourly_schedule JSONB NOT NULL,
  estimated_savings_usd FLOAT,
  efficiency_gain_percent FLOAT,
  reasoning TEXT,
  created_by_agent UUID REFERENCES agents(id),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_energy_schedules_date ON energy_schedules(schedule_date DESC);
CREATE INDEX idx_energy_schedules_pump ON energy_schedules(pump_id);

-- 3. Demand Forecasts Table (AI-generated water demand predictions)
CREATE TABLE IF NOT EXISTS demand_forecasts (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  forecast_date DATE NOT NULL,
  hour INT NOT NULL CHECK (hour >= 0 AND hour < 24),
  predicted_demand FLOAT NOT NULL,
  confidence FLOAT CHECK (confidence >= 0 AND confidence <= 1),
  created_by_agent UUID REFERENCES agents(id),
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(forecast_date, hour)
);

CREATE INDEX idx_demand_forecasts_date ON demand_forecasts(forecast_date DESC);

-- 4. System Metrics Table (for tracking uptime, performance, etc.)
CREATE TABLE IF NOT EXISTS system_metrics (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  metric_type TEXT NOT NULL,
  value FLOAT NOT NULL,
  unit TEXT,
  timestamp TIMESTAMP DEFAULT NOW(),
  metadata JSONB
);

CREATE INDEX idx_system_metrics_type ON system_metrics(metric_type);
CREATE INDEX idx_system_metrics_timestamp ON system_metrics(timestamp DESC);

-- Enable Row Level Security
ALTER TABLE ai_analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE energy_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE demand_forecasts ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_metrics ENABLE ROW LEVEL SECURITY;

-- RLS Policies (allow service role full access)
CREATE POLICY "Enable read access for all users" ON ai_analytics FOR SELECT USING (true);
CREATE POLICY "Enable insert for service role" ON ai_analytics FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for service role" ON ai_analytics FOR UPDATE USING (true);

CREATE POLICY "Enable read access for all users" ON energy_schedules FOR SELECT USING (true);
CREATE POLICY "Enable insert for service role" ON energy_schedules FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for service role" ON energy_schedules FOR UPDATE USING (true);

CREATE POLICY "Enable read access for all users" ON demand_forecasts FOR SELECT USING (true);
CREATE POLICY "Enable insert for service role" ON demand_forecasts FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for service role" ON demand_forecasts FOR UPDATE USING (true);

CREATE POLICY "Enable read access for all users" ON system_metrics FOR SELECT USING (true);
CREATE POLICY "Enable insert for service role" ON system_metrics FOR INSERT WITH CHECK (true);

-- Enable Realtime (optional, for live updates)
ALTER PUBLICATION supabase_realtime ADD TABLE ai_analytics;
ALTER PUBLICATION supabase_realtime ADD TABLE energy_schedules;
ALTER PUBLICATION supabase_realtime ADD TABLE demand_forecasts;
ALTER PUBLICATION supabase_realtime ADD TABLE system_metrics;

COMMENT ON TABLE ai_analytics IS 'Stores AI-generated analytics and metrics for the dashboard';
COMMENT ON TABLE energy_schedules IS 'Stores optimized pump schedules generated by Energy Optimizer Agent';
COMMENT ON TABLE demand_forecasts IS 'Stores 24-hour water demand predictions';
COMMENT ON TABLE system_metrics IS 'Stores system performance metrics like uptime, pressure, etc.';
